const PLUS = 'PLUS';
const MINUS = 'MINUS';
const TIMES = 'TIMES';
const DIVIDE = 'DIVIDE';
const COMPUTE = 'COMPUTE';
const MOVE = 'MOVE';
const MODIFY1 = 'MODIFY1';
const MODIFY2 = 'MODIFY2';

export { PLUS, MINUS, TIMES, DIVIDE, COMPUTE, MOVE, MODIFY1, MODIFY2 };